menu:
  Home: /
  Archives: /archives
  About: /about

widgets:
- search
- category
- tagcloud
- visitor
- recent_posts

excerpt_link: 查看完整文章

#twitter:
#  username:
#  show_replies: false
#  tweet_count: 5

addthis:
  enable: true
  #pubid:
  #facebook:
  #twitter:
  #google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: #facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
